<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Stock;
use App\Models\Unit;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $obj = [
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'แสงโสมกลม',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 320,
                'cost_price' => 0,
                'unit_id' => 'กลม',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'หงส์กลม',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 280,
                'cost_price' => 0,
                'unit_id' => 'กลม',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'เหล้าขาวขวดเล็ก 30 ดีกรี',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 65,
                'cost_price' => 53.50,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'สุราข้าวหอม 40 ดีกรี',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 70,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'สุราข้าวหอม 30 ดีกรี',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 65,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'เบียร์สิงห์',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 69,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'เบียร์ช้าง',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 60,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'เบียร์ลีโอ',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 65,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'โซดา',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'เอ็มร้อย',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 12,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'กาแฟกระป๋องเบอร์ดี้แดง',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 17,
                'cost_price' => 0,
                'unit_id' => 'กระป๋อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'กาแฟกระป๋องเบอร์ดี้เขียว',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 17,
                'cost_price' => 0,
                'unit_id' => 'กระป๋อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'กาแฟกระป๋องเนสเขียว',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 17,
                'cost_price' => 0,
                'unit_id' => 'กระป๋อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'เป๊ปซี่ขวดใหญ่',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 35,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'โค้กขวดใหญ่',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 35,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'น้ำแดงขวดใหญ่',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 35,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'น้ำเขียวขวดใหญ่',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 35,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'น้ำส้มขวดใหญ่',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 35,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'นมเปรี้ยวผลไม้รวมสีเขียว',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 12,
                'cost_price' => 0,
                'unit_id' => 'กล่อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'นมเปรี้ยวส้ม',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 12,
                'cost_price' => 0,
                'unit_id' => 'กล่อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'เย็นๆ',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'อิชิตันน้ำผึ้งมะนาว',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'อิชิตันกรีนทีน',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'บุหรี่',
                'name' => 'บุหรี่ SMS เขียว',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 75,
                'cost_price' => 0,
                'unit_id' => 'ซอง',
                'is_active' => true,
            ],
            [
                'category_id' => 'บุหรี่',
                'name' => 'บุหรี่ SMS แดง',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 75,
                'cost_price' => 0,
                'unit_id' => 'ซอง',
                'is_active' => true,
            ],
            [
                'category_id' => 'บุหรี่',
                'name' => 'ยาเส้น',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 15,
                'cost_price' => 0,
                'unit_id' => 'ซอง',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'น้ำแข็งถุงเล็ก',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 5,
                'cost_price' => 0,
                'unit_id' => 'ถุง',
                'is_active' => true,
            ],
            [
                'category_id' => 'เครื่องดื่ม',
                'name' => 'น้ำแข็งถุงใหญ่',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ถุง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'ถ่านถุง',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 20,
                'cost_price' => 0,
                'unit_id' => 'ถุง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'รสดี 27 บาท',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 27,
                'cost_price' => 0,
                'unit_id' => 'ซอง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'รสดีเล็ก',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 13,
                'cost_price' => 0,
                'unit_id' => 'ซอง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'คนอร์ก้อน',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 7,
                'cost_price' => 0,
                'unit_id' => 'ก้อน',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'ชูรส 10 บาท',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ซอง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'น้ำปลาทิพรส',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 35,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'น้ำกระเทียมดอง',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 15,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'อาหาร',
                'name' => 'ปลากระป๋องสามแม่ครัว',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 25,
                'cost_price' => 0,
                'unit_id' => 'กระป๋อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'น้ำมันพืชขวดใหญ่',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 55,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'น้ำมันพืชขวดกลาง',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 30,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'น้ำมันพืชขวดเล็ก',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 30,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'กะทิ 250 ml',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 26,
                'cost_price' => 0,
                'unit_id' => 'กล่อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'น้ำปลาร้าแม่เรียน',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 30,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'ซีอิ๊วขาว 300 ML',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 35,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'ซอสหอย 300 ML',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 40,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'ซอสภูเขาทอง 200 ml',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 25,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'วุ้นเส้นตาต้นถั่ว',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'พริกป่น',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 25,
                'cost_price' => 0,
                'unit_id' => 'ซอง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'เกลือห่อเล็ก',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 2,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'กะปิ 90 กรัม',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 17,
                'cost_price' => 0,
                'unit_id' => 'กระปุก',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'ซีอิ๊วดำหวาน 280 ML',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 16,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'น้ำส้มสายชู 300 ML',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 13,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'น้ำจิ้มเนื้อวัวน้องพร',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 25,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'แป้งทอดกรอบโกกิ',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 25,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'น้ำตาลปี๊บน้ำตาลปึก',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 25,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'น้ำตาลทราย 1 กิโลกรัม',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 35,
                'cost_price' => 0,
                'unit_id' => 'ถุง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'พริกไทยเม็ดห่อ',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 5,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของชําร่วย',
                'name' => 'แป้งแคร์กลิ่นซากุระ 160 กรัม',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 35,
                'cost_price' => 0,
                'unit_id' => 'กระป๋อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของชําร่วย',
                'name' => 'แป้งแคร์ pink soft 50 กรัม',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 15,
                'cost_price' => 0,
                'unit_id' => 'กระป๋อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของชําร่วย',
                'name' => 'แป้งโพรเทคเย็น 60 กรัม',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 20,
                'cost_price' => 0,
                'unit_id' => 'กระป๋อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของชําร่วย',
                'name' => 'ผ้าอนามัยลอรีเอะ 5 ชิ้น',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'แชมพูซันซิล 110 ml',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 29,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'ครีมนวดผม sunsilk 105 ML',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 29,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'แชมพูเคลียร์ 60 ML',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 25,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'แชมพูรีจอยส์ 70 ML',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 20,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'สบู่นกแก้วสีเขียว',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 25,
                'cost_price' => 0,
                'unit_id' => 'ก้อน',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'สบู่นกแก้วสีชมพู',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 25,
                'cost_price' => 0,
                'unit_id' => 'ก้อน',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'ยาสีฟันคอลเกตเล็ก',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 15,
                'cost_price' => 0,
                'unit_id' => 'หลอด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'กระดาษทิชชูห่อเล็ก',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'ยาจุดกันยุงห่านฟ้า',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 25,
                'cost_price' => 0,
                'unit_id' => 'กล่อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'ซันไลต์ขวดเล็ก',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 12,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'ซันไลต์ 300 ML',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 20,
                'cost_price' => 0,
                'unit_id' => 'ขวด',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'ถุงขยะ 24 * 28 บรรจุ 18 ใบ',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 25,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'ฝอยขัดหม้อ',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 15,
                'cost_price' => 0,
                'unit_id' => 'อัน',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในครัว',
                'name' => 'สก๊อตไบร์ท',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 5,
                'cost_price' => 0,
                'unit_id' => 'อัน',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'ผงซักฟอกอีซี่เล็ก',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ซอง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'น้ำยาปรับผ้านุ่มดาวนี่ดำเล็ก',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ซอง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'น้ำยาปรับผ้านุ่มดาวนี่ชมพู',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ซอง',
                'is_active' => true,
            ],
            [
                'category_id' => 'ของใช้ในบ้าน',
                'name' => 'น้ำยาปรับผ้านุ่มดาวนี่แดง',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 10,
                'cost_price' => 0,
                'unit_id' => 'ซอง',
                'is_active' => true,
            ],
            [
                'category_id' => 'อาหาร',
                'name' => 'มาม่ารสต้มยำน้ำข้น',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 8,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'อาหาร',
                'name' => 'มาม่าต้มยำกุ้ง',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 8,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'อาหาร',
                'name' => 'มาม่าคัพรสต้มยำกุ้ง',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 15,
                'cost_price' => 0,
                'unit_id' => 'กล่อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'อาหาร',
                'name' => 'มาม่ารสหมูสับสีเหลือง',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 8,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'อาหาร',
                'name' => 'มาม่าคัพรสหมูสับ',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 15,
                'cost_price' => 0,
                'unit_id' => 'กล่อง',
                'is_active' => true,
            ],
            [
                'category_id' => 'อาหาร',
                'name' => 'ไวไว',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 8,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'อาหาร',
                'name' => 'ยำยำช้างน้อยเล็ก',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 5,
                'cost_price' => 0,
                'unit_id' => 'ห่อ',
                'is_active' => true,
            ],
            [
                'category_id' => 'อาหาร',
                'name' => 'ไข่ไก่',
                'description' => '-',
                // 'product_code' => 'auto generate,
                'price' => 5,
                'cost_price' => 0,
                'unit_id' => 'ฟอง',
                'is_active' => true,
            ],
        ];

        foreach ($obj as $key) {
            try {
                $category = Category::where('name', $key['category_id'])->first();
                $unit = Unit::where('name', $key['unit_id'])->first();
                $key['category_id'] = $category->id;
                $key['unit_id'] = $unit->id;
                $key['product_code'] = random_int(10000000, 99999999);
                $p = Product::create($key);

                // Insert Stock
                Stock::updateOrCreate([
                    'product_id' => $p->id,
                ], [
                    'category_id' => $category->id,
                    'product_id' => $p->id,
                    'unit_id' => $unit->id,
                    'is_active' => true,
                ]);
            } catch (\Exception $e) {
            }
        }
    }
}
